# syntax=docker/dockerfile:1
FROM nginx:alpine
RUN apk add --no-cache ca-certificates
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY web/ /usr/share/nginx/html
EXPOSE 80
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]
